# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(default='title', max_length=20),
        ),
    ]
